# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edde3a1360df850b501ff486dfe1d3ec94d598885c345ed7a1168f2ef2086a3379b3082bcc4cb5f480b917dc6c666ab45f696750aed73e0402bd84833e0723f3

test:
  secret_key_base: 99c3a97bcf5adf06eea53523240718ae95ab71204b14a3fb10c45abda9c7c290951a5fb3f73fda0327c844db429039f55cea352ddaeae562e7d22f6b21d6189e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
